apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
# sample1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-echo-1
  namespace: sample
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: sample
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: hoge.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: service-echo-1
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-echo-1
  namespace: sample
spec:
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
  type: NodePort
  selector:
    name: app-echo-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-echo-1
  namespace: sample
spec:
  selector:
    matchLabels:
      name: app-echo-1
  replicas: 2
  template:
    metadata:
      labels:
        name: app-echo-1
    spec:
      containers:
        - name: app-echo-1
          image: hashicorp/http-echo
          args:
            - "-text=sample1"

---
# sample2
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-echo-2
  namespace: sample
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: sample
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: fuga.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: service-echo-2
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-echo-2
  namespace: sample
spec:
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
  type: NodePort
  selector:
    name: app-echo-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-echo-2
  namespace: sample
spec:
  selector:
    matchLabels:
      name: app-echo-2
  replicas: 2
  template:
    metadata:
      labels:
        name: app-echo-2
    spec:
      containers:
        - name: app-echo-2
          image: hashicorp/http-echo
          args:
            - "-text=sample2"
