apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample
  region: ap-northeast-1
  version: "1.18"

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
    subnets:
      - subnet-xxx4
      - subnet-xxx5
      - subnet-xxx6
  - name: fp-sample
    selectors:
      - namespace: sample
    subnets:
      - subnet-xxx4
      - subnet-xxx5
      - subnet-xxx6